{% set version = "2.3.7" %}

package:
  name: pathlib2
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pathlib2/pathlib2-{{ version }}.tar.gz
  sha256: 7a4329d67beff9a712e1d3ae147e4e3e108b0bfd284ffdea03a635126c76b3c0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - six
    - scandir  # [py27]

test:
  imports:
    - pathlib2

about:
  home: https://github.com/mcmtroffaes/pathlib2
  license: MIT
  license_file: LICENSE.rst
  summary: Fork of pathlib aiming to support the full stdlib Python API

extra:
  recipe-maintainers:
    - pelson
    - takluyver
