{% set version = "2.3.4" %}

package:
  name: pathlib2
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pathlib2/pathlib2-{{ version }}.tar.gz
  sha256: 446014523bb9be5c28128c4d2a10ad6bb60769e78bd85658fe44a450674e0ef8

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six
    - scandir  # [py27]

test:
  imports:
    - pathlib2

about:
  home: https://github.com/mcmtroffaes/pathlib2
  license: MIT
  license_file: LICENSE.rst
  summary: "Fork of pathlib aiming to support the full stdlib Python API"

extra:
  recipe-maintainers:
    - pelson
    - takluyver
