{% set version = "2.3.6" %}

package:
  name: pathlib2
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pathlib2/pathlib2-{{ version }}.tar.gz
  sha256: 7d8bcb5555003cdf4a8d2872c538faa3a0f5d20630cb360e518ca3b981795e5f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - six
    - scandir  # [py27]

test:
  imports:
    - pathlib2

about:
  home: https://github.com/mcmtroffaes/pathlib2
  license: MIT
  license_file: LICENSE.rst
  summary: Fork of pathlib aiming to support the full stdlib Python API

extra:
  recipe-maintainers:
    - pelson
    - takluyver
